### PR TITLE
Unused code in OculusRiftControls?

### PR DESCRIPTION
**Pull request by mrdoob**

### CODE REVIEW

**Comment by mrdoob** [comment]
This is great by the way! ^^

**Comment by mrdoob** [comment]
Actually, why is the quaternion code in the effect instead of in the controls?

**Comment by benvanik** [comment]
I don't think I ever got a chance to finish the controls - they could definitely use some work!
I think this code here was supposed to fix it (make you move in the direction of the HMD), but I'm not sure the math worked out right/I couldn't figure out how to transform the threejs scene right :(

**Comment by mrdoob** [comment]
Ah! Now I understand what you were trying to do :)

**Comment by mrdoob** [comment]
I'll try to find some time and clean this up.

**Comment by benvanik** [comment]
Awesome :heart:

**Pull request closed without merging**
